add_test( SymTableTestFixture.CreateSubTableTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=SymTableTestFixture.CreateSubTableTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( SymTableTestFixture.CreateSubTableTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SymTableTestFixture.InsertAndLookupTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=SymTableTestFixture.InsertAndLookupTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( SymTableTestFixture.InsertAndLookupTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SymTableTestFixture.RemoveTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=SymTableTestFixture.RemoveTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( SymTableTestFixture.RemoveTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSymNodeTestFixture.GetBasicTypeNameTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=IntSymNodeTestFixture.GetBasicTypeNameTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSymNodeTestFixture.GetBasicTypeNameTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSymNodeTestFixture.GetTypeSizeTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=IntSymNodeTestFixture.GetTypeSizeTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSymNodeTestFixture.GetTypeSizeTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSymNodeTestFixture.GetUpperBoundTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=IntSymNodeTestFixture.GetUpperBoundTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSymNodeTestFixture.GetUpperBoundTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSymNodeTestFixture.GetLowerBoundTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=IntSymNodeTestFixture.GetLowerBoundTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSymNodeTestFixture.GetLowerBoundTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( BitSymNodeTest.ConstructorTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=BitSymNodeTest.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( BitSymNodeTest.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( VarSymNodeTest.CreateSymbolTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=VarSymNodeTest.CreateSymbolTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( VarSymNodeTest.CreateSymbolTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( VarSymNodeTest.ConstructorTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=VarSymNodeTest.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( VarSymNodeTest.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( VarSymNodeTest.CastToTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=VarSymNodeTest.CastToTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( VarSymNodeTest.CastToTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( VarSymNodeTest.GetSizeOfTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=VarSymNodeTest.GetSizeOfTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( VarSymNodeTest.GetSizeOfTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( VarSymNodeTest.PrintGraphVizTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=VarSymNodeTest.PrintGraphVizTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( VarSymNodeTest.PrintGraphVizTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SymbolTestFixture.ConstructorTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=SymbolTestFixture.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( SymbolTestFixture.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SymbolTestFixture.ParentTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=SymbolTestFixture.ParentTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( SymbolTestFixture.ParentTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FSMTest.BuildFSMTransitionsTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FSMTest.BuildFSMTransitionsTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FSMTest.BuildFSMTransitionsTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FSMTest.BuildFSM_usingCreateEdgeTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FSMTest.BuildFSM_usingCreateEdgeTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FSMTest.BuildFSM_usingCreateEdgeTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmEdgeTest.ConstructorTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmEdgeTest.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmEdgeTest.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmEdgeTest.ChangeTargetTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmEdgeTest.ChangeTargetTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmEdgeTest.ChangeTargetTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmEdgeTest.ChangeSourceTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmEdgeTest.ChangeSourceTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmEdgeTest.ChangeSourceTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.CreateFsmEdgeTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.CreateFsmEdgeTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.CreateFsmEdgeTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.CopyFsmEdgeTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.CopyFsmEdgeTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.CopyFsmEdgeTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.AddTransitionTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.AddTransitionTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.AddTransitionTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.RemoveTransitionTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.RemoveTransitionTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.RemoveTransitionTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.AddInputTransitionTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.AddInputTransitionTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.AddInputTransitionTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.RemoveInputTransitionTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.RemoveInputTransitionTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.RemoveInputTransitionTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.GetFlagsTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.GetFlagsTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.GetFlagsTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.IsAcceptingTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.IsAcceptingTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.IsAcceptingTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.IsProgressTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.IsProgressTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.IsProgressTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.IsDeterministicTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.IsDeterministicTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.IsDeterministicTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.IsAtomicTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.IsAtomicTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.IsAtomicTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.SetLineNbTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.SetLineNbTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.SetLineNbTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.GetParentTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.GetParentTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.GetParentTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.OrderAcceptingTransitionsTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.OrderAcceptingTransitionsTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.OrderAcceptingTransitionsTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.GetIDTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.GetIDTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.GetIDTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FsmNodeTest.EqualityOperatorTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=FsmNodeTest.EqualityOperatorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FsmNodeTest.EqualityOperatorTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ADDUtilsTests.impliesTest /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=ADDUtilsTests.impliesTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( ADDUtilsTests.impliesTest PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TraceTest.AddTransition /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=TraceTest.AddTransition]==] --gtest_also_run_disabled_tests)
set_tests_properties( TraceTest.AddTransition PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TraceTest.AddState /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=TraceTest.AddState]==] --gtest_also_run_disabled_tests)
set_tests_properties( TraceTest.AddState PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TraceTest.AddTrace /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=TraceTest.AddTrace]==] --gtest_also_run_disabled_tests)
set_tests_properties( TraceTest.AddTrace PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TraceTest.EqualityOperator /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=TraceTest.EqualityOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties( TraceTest.EqualityOperator PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TraceTest.InequalityOperatorAdvanced /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=TraceTest.InequalityOperatorAdvanced]==] --gtest_also_run_disabled_tests)
set_tests_properties( TraceTest.InequalityOperatorAdvanced PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TraceTest.InequalityOperator /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=TraceTest.InequalityOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties( TraceTest.InequalityOperator PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TraceTest.PrintCSV /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=TraceTest.PrintCSV]==] --gtest_also_run_disabled_tests)
set_tests_properties( TraceTest.PrintCSV PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TraceReportTest.Test /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=TraceReportTest.Test]==] --gtest_also_run_disabled_tests)
set_tests_properties( TraceReportTest.Test PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TraceReportTest.AddBadTraceAndGetBadTraces /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=TraceReportTest.AddBadTraceAndGetBadTraces]==] --gtest_also_run_disabled_tests)
set_tests_properties( TraceReportTest.AddBadTraceAndGetBadTraces PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TraceReportTest.AddGoodTraceAndGetGoodTraces /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=TraceReportTest.AddGoodTraceAndGetGoodTraces]==] --gtest_also_run_disabled_tests)
set_tests_properties( TraceReportTest.AddGoodTraceAndGetGoodTraces PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( StateToGraphVizTest.Construction /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=StateToGraphVizTest.Construction]==] --gtest_also_run_disabled_tests)
set_tests_properties( StateToGraphVizTest.Construction PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( StateToGraphVizTest.PrintGraphViz /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=StateToGraphVizTest.PrintGraphViz]==] --gtest_also_run_disabled_tests)
set_tests_properties( StateToGraphVizTest.PrintGraphViz PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( StateTest.DefaultConstructor /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=StateTest.DefaultConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties( StateTest.DefaultConstructor PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( StateTest.CopyConstructor /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=StateTest.CopyConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties( StateTest.CopyConstructor PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ElementStackTest.PushAndTop /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=ElementStackTest.PushAndTop]==] --gtest_also_run_disabled_tests)
set_tests_properties( ElementStackTest.PushAndTop PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ElementStackTest.IsIn /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=ElementStackTest.IsIn]==] --gtest_also_run_disabled_tests)
set_tests_properties( ElementStackTest.IsIn PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ElementStackTest.Empty /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=ElementStackTest.Empty]==] --gtest_also_run_disabled_tests)
set_tests_properties( ElementStackTest.Empty PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ElementStackTest.Pop /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=ElementStackTest.Pop]==] --gtest_also_run_disabled_tests)
set_tests_properties( ElementStackTest.Pop PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MutantGenerationTest.LoadValidPromelaFile /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=MutantGenerationTest.LoadValidPromelaFile]==] --gtest_also_run_disabled_tests)
set_tests_properties( MutantGenerationTest.LoadValidPromelaFile PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ExploreTest.Explore /home/slazreg/Work/Research/Daedalux/tests/test_suite [==[--gtest_filter=ExploreTest.Explore]==] --gtest_also_run_disabled_tests)
set_tests_properties( ExploreTest.Explore PROPERTIES WORKING_DIRECTORY /home/slazreg/Work/Research/Daedalux/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( test_suite_TESTS SymTableTestFixture.CreateSubTableTest SymTableTestFixture.InsertAndLookupTest SymTableTestFixture.RemoveTest IntSymNodeTestFixture.GetBasicTypeNameTest IntSymNodeTestFixture.GetTypeSizeTest IntSymNodeTestFixture.GetUpperBoundTest IntSymNodeTestFixture.GetLowerBoundTest BitSymNodeTest.ConstructorTest VarSymNodeTest.CreateSymbolTest VarSymNodeTest.ConstructorTest VarSymNodeTest.CastToTest VarSymNodeTest.GetSizeOfTest VarSymNodeTest.PrintGraphVizTest SymbolTestFixture.ConstructorTest SymbolTestFixture.ParentTest FSMTest.BuildFSMTransitionsTest FSMTest.BuildFSM_usingCreateEdgeTest FsmEdgeTest.ConstructorTest FsmEdgeTest.ChangeTargetTest FsmEdgeTest.ChangeSourceTest FsmNodeTest.CreateFsmEdgeTest FsmNodeTest.CopyFsmEdgeTest FsmNodeTest.AddTransitionTest FsmNodeTest.RemoveTransitionTest FsmNodeTest.AddInputTransitionTest FsmNodeTest.RemoveInputTransitionTest FsmNodeTest.GetFlagsTest FsmNodeTest.IsAcceptingTest FsmNodeTest.IsProgressTest FsmNodeTest.IsDeterministicTest FsmNodeTest.IsAtomicTest FsmNodeTest.SetLineNbTest FsmNodeTest.GetParentTest FsmNodeTest.OrderAcceptingTransitionsTest FsmNodeTest.GetIDTest FsmNodeTest.EqualityOperatorTest ADDUtilsTests.impliesTest TraceTest.AddTransition TraceTest.AddState TraceTest.AddTrace TraceTest.EqualityOperator TraceTest.InequalityOperatorAdvanced TraceTest.InequalityOperator TraceTest.PrintCSV TraceReportTest.Test TraceReportTest.AddBadTraceAndGetBadTraces TraceReportTest.AddGoodTraceAndGetGoodTraces StateToGraphVizTest.Construction StateToGraphVizTest.PrintGraphViz StateTest.DefaultConstructor StateTest.CopyConstructor ElementStackTest.PushAndTop ElementStackTest.IsIn ElementStackTest.Empty ElementStackTest.Pop MutantGenerationTest.LoadValidPromelaFile ExploreTest.Explore)
