if(EXISTS "/home/slazreg/Work/Research/Daedalux/tests/test_suite[1]_tests.cmake")
  include("/home/slazreg/Work/Research/Daedalux/tests/test_suite[1]_tests.cmake")
else()
  add_test(test_suite_NOT_BUILT test_suite_NOT_BUILT)
endif()
