#include "stateVisitor.hpp"
#include "state.hpp"
#include "programState.hpp"
#include "initState.hpp"
#include "compositeState.hpp"
#include "payload.hpp"
#include "process.hpp"
#include "transition.hpp"
#include "variable.hpp"
#include "utypeVariable.hpp"
#include "boolVariable.hpp"
#include "mtypeVariable.hpp"
#include "channel.hpp"
#include "featuredStateDecorator.hpp"

