#include "state.hpp"
#include "programState.hpp"
#include "payload.hpp"
#include "process.hpp"
#include "transition.hpp"
#include "variable.hpp"
#include "utypeVariable.hpp"
#include "boolVariable.hpp"
#include "mtypeVariable.hpp"
#include "channel.hpp"

