name: Daedalux CI

on:
  workflow_dispatch:
  push:
    branches: [ alpha ]
  pull_request:
    branches: [ alpha ]

jobs:
  build-project:
    name: Build on ${{ matrix.os }} [${{ matrix.build_type }}]
    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake
        uses: kitware/setup-cmake@v1
        with:
          cmake-version: '3.25.0'

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure --parallel

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.build_type }}
          path: build/Testing/Temporary/

      - name: Upload compile_commands.json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compile_commands-${{ matrix.os }}-${{ matrix.build_type }}
          path: build/compile_commands.json
