name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          build-dir: build

      - name: Build Project
        run: cmake --build build

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/Testing/Temporary
